apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: resturantapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resturantapp 
    spec:
      containers:
        - name: resturantapp 
          image: azcnddemo.azurecr.io/resturantapp
          ports:
          - containerPort: 8080